### ISSUE TITLE
google-map element in hidden state

### ISSUE THREAD

**Issue by piotrdubiel** [Polymer/core-animated-pages#10]
Recently I had a problem with using google-map element inside core-animated-pages. I have layout like this:

``` html
<section is="list">
   (...)
</section>
<section id="details">
    <google-map></google-map>
</section>
```

Initially `#list` is selected, but when I select `#details`, map shows up in weird state.
![screen shot 2014-07-15 at 19 01 38](https://cloud.githubusercontent.com/assets/1955710/3588256/c59941b8-0c41-11e4-8636-3d5d00fef71f.png)
I suspect that it's because map element renders when its parent has set `display: none`;
If I change

``` css
::content > *:not(.core-selected):not([animate]) {
  display: none !important;
}
```

to

``` css
::content > *:not(.core-selected):not([animate]) {
   visibility: hidden !important;
}
```

in core-animated-pages.css, then everything is ok.
What's the best approach to fix this?
